//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAgendaDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public int Empleado_Id { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
